#!/usr/bin/env ruby
require 'fileutils'

# Accept input app and output path
unless ARGV.length == 2
  puts "Usage: #{$0} Original.app Unsigned-clone.app"
  exit
end

input_path = ARGV[0]
output_path = ARGV[1]

# Create directory for unsigned clone
output_path_contents = File.join(output_path, 'Contents')
output_path_binaries = File.join(output_path_contents, 'MacOS')
FileUtils.mkdir_p(output_path_binaries)

# Create clone of app using symlinks
contents_entries = Dir[File.join(input_path, 'Contents/*')].reject { |e| File.basename(e) == 'MacOS' }
FileUtils.ln_s(contents_entries, output_path_contents)

# Create unsigned copy of app binaries
unsign_binary = File.join(File.dirname(__FILE__), 'bin/unsign')
Dir[File.join(input_path, 'Contents/MacOS/*')].each do |binary_file|
  output_file = File.join(output_path_binaries, File.basename(binary_file))
  %x(#{unsign_binary} #{binary_file} #{output_file})
end
